FROM debian:stretch

RUN apt update && apt install -y \
        curl \
        git \
        build-essential \
        cmake \
        jq \
        mosquitto-clients \
        python3-dev \
        python3-pillow \
        python3-pip
        
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY src/  /opt/
COPY icons/ /opt/mypanel-icons/
COPY conf/ /opt/mypanel-conf/

RUN cd /opt/led-matrix/ && \
    make -C examples-api-use
    
RUN cd /opt/led-matrix/ && \
    make build-python PYTHON=$(command -v python3) && \
    make install-python PYTHON=$(command -v python3)
    
RUN python3 -m pip install requests

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=1m \
    --retries=3 \
  CMD /opt/healthcheck

WORKDIR /opt
ENTRYPOINT ["/bin/bash", "/opt/mqtt/entrypoint.sh"]
